experimentName: TimesNet Hyper Tune
searchSpace:
  seq_len:
    _type: choice
    _value: [100, 50, 25, 10]
  lr:
    _type: loguniform
    _value: [1e-4, 1e-2]
  epochs:
    _type: choice
    _value: [5, 10, 15]
  batch_size:
    _type: choice
    _value: [32, 64, 128]
  epoch_steps:
    _type: choice
    _value: [10, 20, 30, 40, 50]
  e_layers:
    _type: choice
    _value: [2, 3, 4]
  d_model:
    _type: choice
    _value: [64, 128, 256]
  d_ff:
    _type: choice
    _value: [64, 128, 256]
  dropout:
    _type: uniform
    _value: [0.1, 0.3]
  top_k:
    _type: randint
    _value: [3, 11]
  num_kernels:
    _type: choice
    _value: [3, 6, 12]
  percentile:
    _type: uniform
    _value: [96, 99]
trialCommand: python timesnet.py
trialCodeDirectory: .
#trialGpuNumber: 0
trialConcurrency: 1
maxTrialNumber: 1
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
