experimentName: TimesNet Hyper Tune
searchSpace:
  seq_len:
    _type: choice
    _value: [20]
  lr:
    _type: loguniform
    _value: [1e-4, 1e-2]
  #epochs:
  #  _type: choice
  #  _value: [5, 10, 15]
  batch_size:
    _type: choice
    _value: [64]
  epoch_steps:
    _type: choice
    _value: [40]
  e_layers:
    _type: choice
    _value: [2, 3]
  d_model:
    _type: choice
    _value: [256]
  d_ff:
    _type: choice
    _value: [64]
  dropout:
    _type: uniform
    _value: [0.1, 0.2]
  top_k:
    _type: choice
    _value: [6, 7, 8]
  num_kernels:
    _type: choice
    _value: [6]
  percentile:
    _type: uniform
    _value: [98.5, 99.5]
  patience:
    _type: choice
    _value: [3, 5, 7]
  delta:
    _type: uniform
    _value: [1e-6, 5e-6]
trialCommand: python gnss_ad_timesnet.py
trialCodeDirectory: .
#trialGpuNumber: 0
trialConcurrency: 1
maxTrialNumber: 2
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
