experimentName: TimesNet Hyper Tune
searchSpace:
  dropout:
    _type: quniform
    _value: [0.1, 0.5, 0.05]
  top_k:
    _type: choice
    _value: [3, 5]
  percentile:
    _type: quniform
    _value: [99, 99.9, 0.1]
trialCommand: python nni_experiment/nni_timesnet_experiment.py
trialCodeDirectory: ../
#trialGpuNumber: 0
trialConcurrency: 1
maxTrialNumber: 50
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
