experimentName: TimesNet Hyper Tune
searchSpace:
  seq_len:
    _type: randint
    _value: [10, 20]
  e_layers:
    _type: choice
    _value: [2, 3]
  d_model:
    _type: choice
    _value: [32, 64, 128]
  d_ff:
    _type: choice
    _value: [64, 128]
  dropout:
    _type: uniform
    _value: [0.1, 0.5]
  top_k:
    _type: choice
    _value: [3, 5]
  percentile:
    _type: uniform
    _value: [99, 99.9]
trialCommand: python nni_experiment/nni_timesnet_experiment.py
trialCodeDirectory: ../
#trialGpuNumber: 0
trialConcurrency: 1
maxTrialNumber: 50
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
