experimentName: TimesNet Hyper Tune
searchSpace:
  seq_len:
    _type: choice
    _value: [20]
  lr:
    _type: choice
    _value: [2.8e-4]
  #epochs:
  #  _type: choice
  #  _value: [5, 10, 15]
  batch_size:
    _type: choice
    _value: [64]
  epoch_steps:
    _type: choice
    _value: [40]
  e_layers:
    _type: choice
    _value: [3]
  d_model:
    _type: choice
    _value: [512]
  d_ff:
    _type: choice
    _value: [64]
  dropout:
    _type: uniform
    _value: [0.25]
  top_k:
    _type: choice
    _value: [6]
  num_kernels:
    _type: choice
    _value: [3]
  percentile:
    _type: uniform
    _value: [96, 99.9]
  patience:
    _type: choice
    _value: [5, 7]
  delta:
    _type: choice
    _value: [2.0e-6]
trialCommand: python nni_experiment/gnss_ad_timesnet.py
trialCodeDirectory: .
#trialGpuNumber: 0
trialConcurrency: 1
maxTrialNumber: 1
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
